### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by aurelien-reeves-scalingo** [tmzane/musttag#38] opened 2023-03-27 09:54 UTC
Hi,

Looks like #20, but I was not able to identify what's going on on our side, I am not able to have a minimal reproducible example

Here's the stacktrace we are facing:

```
ERRO [runner] Panic: musttag: package "packagename" (isInitialPkg: true, needAnalyzeSource: true): runtime error: invalid memory address or nil pointer dereference: goroutine 63072 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x65
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyzeSafe.func1()
        /home/aurelien/go/pkg/mod/github.com/golangci/golangci-lint@v1.52.2/pkg/golinters/goanalysis/runner_action.go:109 +0x285
panic({0x15dc7e0, 0x212a260})
        /usr/local/go/src/runtime/panic.go:884 +0x212
go/types.(*Package).Path(...)
        /usr/local/go/src/go/types/package.go:31
github.com/junk1tm/musttag.(*checker).parseStructType(0xc0363a74f0?, {0x19bccc0?, 0xc0001cc540?}, 0x1f?)
        /home/aurelien/go/pkg/mod/github.com/junk1tm/musttag@v0.5.0/musttag.go:195 +0x99
github.com/junk1tm/musttag.run.func1({0x19bc298?, 0xc0363e60c0})
        /home/aurelien/go/pkg/mod/github.com/junk1tm/musttag@v0.5.0/musttag.go:150 +0x2c8
golang.org/x/tools/go/ast/inspector.(*Inspector).Preorder(0xc0217ffec0, {0xc0030799e8?, 0x1?, 0x8c878e?}, 0xc0030799f8)
        /home/aurelien/go/pkg/mod/golang.org/x/tools@v0.7.0/go/ast/inspector/inspector.go:81 +0xa8
github.com/junk1tm/musttag.run(0xc043b0a0f0, 0xc003079b28)
        /home/aurelien/go/pkg/mod/github.com/junk1tm/musttag@v0.5.0/musttag.go:108 +0x15d
github.com/junk1tm/musttag.New.func1(0xc043b0a0f0?)
        /home/aurelien/go/pkg/mod/github.com/junk1tm/musttag@v0.5.0/musttag.go:54 +0x125
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyze(0xc005fb6180)
        /home/aurelien/go/pkg/mod/github.com/golangci/golangci-lint@v1.52.2/pkg/golinters/goanalysis/runner_action.go:195 +0xa22
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyzeSafe.func2()
        /home/aurelien/go/pkg/mod/github.com/golangci/golangci-lint@v1.52.2/pkg/golinters/goanalysis/runner_action.go:113 +0x1d
github.com/golangci/golangci-lint/pkg/timeutils.(*Stopwatch).TrackStage(0xc00281f4f0, {0x172f703, 0x7}, 0xc004f47f48)
        /home/aurelien/go/pkg/mod/github.com/golangci/golangci-lint@v1.52.2/pkg/timeutils/stopwatch.go:111 +0x4a
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyzeSafe(0xc0026da9c0?)
        /home/aurelien/go/pkg/mod/github.com/golangci/golangci-lint@v1.52.2/pkg/golinters/goanalysis/runner_action.go:112 +0x85
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*loadingPackage).analyze.func2(0xc005fb6180)
        /home/aurelien/go/pkg/mod/github.com/golangci/golangci-lint@v1.52.2/pkg/golinters/goanalysis/runner_loadingpackage.go:80 +0xb4
created by github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*loadingPackage).analyze
        /home/aurelien/go/pkg/mod/github.com/golangci/golangci-lint@v1.52.2/pkg/golinters/goanalysis/runner_loadingpackage.go:75 +0x208 
WARN [runner] Can't run linter goanalysis_metalinter: goanalysis_metalinter: musttag: package "packagename" (isInitialPkg: true, needAnalyzeSource: true): runtime error: invalid memory address or nil pointer dereference 
ERRO Running error: 1 error occurred:
        * can't run linter goanalysis_metalinter: goanalysis_metalinter: musttag: package "packagename" (isInitialPkg: true, needAnalyzeSource: true): runtime error: invalid memory address or nil pointer dereference
```

**Comment by junk1tm** [comment] 2023-03-28 08:51
Hey, thank you for the report, I'll take a look 👍

**Comment by junk1tm** [comment] 2023-03-28 10:55
Unfortunately, I wasn't able to reproduce the panic, but it looks like #39 will be enough to fix it.

@aurelien-reeves-scalingo could you please build `musttag` from the PR above and rerun it on the same codebase?

**Comment by aurelien-reeves-scalingo** [comment] 2023-03-28 13:26
I am deeply sorry but I do not reproduce the error anymore, so I cannot tell if the fix is enough or not.

I did a lot of changes in the meantime, I'll do my best to identify and revert to a reproducible state, but I cannot promise anything at the moment

**Comment by junk1tm** [comment] 2023-03-30 08:22
Thank you, I appreciate your time!

Even if we won't be able to reproduce it, there was a bug indeed (it's clear from the docs the used function may return nil) and #39 is the fix.

I'll leave the issue open for now, in case you have anything to add or somebody else faces it.

**Comment by tmzane** [comment] 2023-04-21 08:38
As #39 has been merged, it looks like we're good here. Feel free to reopen the issue otherwise.

**Closed by tmzane** 2023-04-21 08:38 UTC
Labels: bug
